/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auto-fill`; params?: Router.UnknownInputParams; } | { pathname: `/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/document-vault`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/preview`; params?: Router.UnknownInputParams; } | { pathname: `/region-compare`; params?: Router.UnknownInputParams; } | { pathname: `/stack-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/apply-assistant`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownInputParams; } | { pathname: `/programs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auto-fill`; params?: Router.UnknownOutputParams; } | { pathname: `/calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/document-vault`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/preview`; params?: Router.UnknownOutputParams; } | { pathname: `/region-compare`; params?: Router.UnknownOutputParams; } | { pathname: `/stack-calculator`; params?: Router.UnknownOutputParams; } | { pathname: `/apply-assistant`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/programs/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auto-fill${`?${string}` | `#${string}` | ''}` | `/calculator${`?${string}` | `#${string}` | ''}` | `/document-vault${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/preview${`?${string}` | `#${string}` | ''}` | `/region-compare${`?${string}` | `#${string}` | ''}` | `/stack-calculator${`?${string}` | `#${string}` | ''}` | `/apply-assistant${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manage${`?${string}` | `#${string}` | ''}` | `/manage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/step2${`?${string}` | `#${string}` | ''}` | `/onboarding/step3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auto-fill`; params?: Router.UnknownInputParams; } | { pathname: `/calculator`; params?: Router.UnknownInputParams; } | { pathname: `/document-vault`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/preview`; params?: Router.UnknownInputParams; } | { pathname: `/region-compare`; params?: Router.UnknownInputParams; } | { pathname: `/stack-calculator`; params?: Router.UnknownInputParams; } | { pathname: `/apply-assistant`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage` | `/manage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownInputParams; } | `/programs/${Router.SingleRoutePart<T>}` | { pathname: `/programs/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
